# Generated by Django 6.1 on 2026-09-02 13:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit Indian number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('location', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_open', models.BooleanField(default=True)),
                ('services', models.JSONField(default=list, help_text='List of services, e.g. ["Oil Change", "Tyre Repair"]')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit Indian number starting with 6-9.', regex='^[6-9]\\d{9}$')])),
                ('vehicle_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid vehicle number, e.g. UP16AB1234.', regex='^[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4}$')])),
                ('service', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='mechanics.mechanic')),
            ],
        ),
    ]
