# Generated by Django 6.1 on 2026-09-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['id']},
        ),
    ]
